version: '2.1'

networks:
  monitor-net:
    driver: bridge

volumes:

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      #- /cgroup:/cgroup:ro #doesn't work on MacOS only for Linux
    restart: unless-stopped
    expose:
      - 8080

  sysbench:
    container_name: sysbench_aline
    image: moreiraal/sysbench
    stdin_open: true
    tty: true
 


